version: 2

project_name: pgbase

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_noncgo
    main: ./examples/base
    binary: pgbase
    ldflags:
      - -s -w -X github.com/thewandererbg/pgbase.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

release:
  draft: true

archives:
  - id: archive_noncgo
    builds: [build_noncgo]
    format: zip
    files:
      - LICENSE.md
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^examples:"
      - "^ui:"
